In [2]:
import netCDF4 as nc
import numpy as np
import matplotlib.pyplot as pl
import pandas as pd
import os

In [1]:
# Copied all files to:
allL2Dir = '/disk02/UNCERTAINTIES/Monte-Carlo/Matchups/L2/AllFiles/'
# Goal, load l2 files sequentially
# in each case, find out whether latitude/longitude checks out -> re-read Proctor's email
# in any case get median rrs_vvv and rrs_unc_vvv, 
# then compare to the tabulated matchup data incl. in_situ_rrs_vvv
# and seawifs_rrs_vvv

In [ ]:
df = pd.read_pickle('dfMatchUpSWF.pkl')

In [3]:
ds = nc.Dataset(fname)
ds.groups.keys()

odict_keys(['sensor_band_parameters', 'scan_line_attributes', 'geophysical_data', 'navigation_data', 'processing_control'])

In [4]:
gpv = ds.groups['geophysical_data'].variables

In [5]:
nav = ds.groups['navigation_data'].variables

In [6]:
l2flags = gpv['l2_flags'][:]
rrs412 = gpv['Rrs_412'][:]
rrs412Unc = gpv['Rrs_unc_412'][:]

In [7]:
latitude=nav['latitude'][:]

In [8]:
longitude=nav['longitude'][:]

In [9]:
latitude.shape,longitude.shape

((101, 101), (101, 101))

In [10]:
df = pd.read_pickle('dfMatchUpSWF.pkl')

-120.78572

In [17]:
df_S2001268195215 = df[df['file_name'].str.contains('S2001268195215')]

In [19]:
df_S2001268195215.insitu_Rrs412

id
2725    0.003913
2726    0.003901
Name: insitu_Rrs412, dtype: float64

In [20]:
df_S2001268195215.seawifs_Rrs412

id
2725    0.001941
2726    0.001777
Name: seawifs_Rrs412, dtype: float64

In [27]:
print('rrs412: %f' % np.median(rrs412.compressed()))
print('rrs412_unc: %f' % np.median(rrs412Unc.compressed()))


rrs412: -0.000263
rrs412_unc: 0.000140


In [15]:
ser0 = df[df['L1_name'].str.contains(fId)]

In [20]:
lat0,lon0 = ser0.latitude.values,ser0.longitude.values

In [21]:
lat0,lon0

(array([ 32.912]), array([-117.393]))

In [25]:
a = abs(latitude - lat0) + abs(longitude - lon0)
i,j = np.unravel_index(a.argmin(),a.shape)

In [26]:
i,j

(51, 49)

In [36]:
i5r,j5c = (np.arange(i-2,i+3),np.arange(j-2,j+3))
print(i5r,j5c)

[49 50 51 52 53] [47 48 49 50 51]


In [38]:
I5R,J5C = np.meshgrid(i5r,j5c)

In [27]:
print(latitude[i,j],longitude[i,j])

32.9179 -117.414


In [39]:
l2flags[I5R,J5C]

array([[  0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0],
       [256, 256, 256,   0, 256],
       [256, 256, 256, 256, 256]], dtype=int32)

In [41]:
rrs412[I5R,J5C]

masked_array(data =
 [[0.006080001592636108 0.006182000041007996 0.005580000579357147
  0.005573999136686325 0.0062160007655620575]
 [0.00571800023317337 0.005529999732971191 0.005860000848770142
  0.00610000267624855 0.006136000156402588]
 [0.0044899992644786835 0.004716001451015472 0.005164001137018204
  0.005432002246379852 0.006101999431848526]
 [0.00380600243806839 0.0031560026109218597 0.003600001335144043
  0.0045500025153160095 0.0053800009191036224]
 [0.003962002694606781 0.0037240013480186462 0.0038520023226737976
  0.003280002623796463 0.0040540024638175964]],
             mask =
 [[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]],
       fill_value = 1e+20)

In [42]:
rrs412Unc[I5R,J5C]

masked_array(data =
 [[-- -- -- -- --]
 [-- -- -- -- --]
 [-- -- -- -- --]
 [-- -- -- -- --]
 [-- -- -- -- --]],
             mask =
 [[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]],
       fill_value = 1e+20)

In [45]:
gpv['Rrs_unc_443'][:]

masked_array(data =
 [[-- -- -- ..., -- -- --]
 [-- -- -- ..., -- -- --]
 [-- -- -- ..., -- -- --]
 ..., 
 [-- -- -- ..., -- -- --]
 [-- -- -- ..., -- -- --]
 [-- -- -- ..., -- -- --]],
             mask =
 [[ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]
 ..., 
 [ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]],
       fill_value = 1e+20)